# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Cleanup
      run: rm -rf target/*jar
    - name: Propagate version
      run: mvn -Dbuild.setVersion=0.0.0 install
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: "[Launcher Win] Setup dotnet"
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'
    - name: "[Launcher Win] Install dependencies"
      run: dotnet restore launcher/win/
    - name: "[Launcher Win] Build"
      run: dotnet build launcher/win/

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            launcher/win/Launcher/bin/Debug/net45/Launcher.exe
            launcher/linux/launcher.sh
            target/*.jar
      
